### ISSUE TITLE
ConnectionError: Connection is closed.

### ISSUE THREAD

**Issue by seth350** [bestlong/node-red-contrib-mssql-plus#2] opened 2018-11-19 16:20 UTC
Using:
Raspberry Pi 3 B+
Latest Raspbian Image
Node-Red v0.19.2
node-red-contrib-mssql-plus v0.0.12
mssql v3.3.0

I have total of four mssql-plus nodes in a flow. None of them are activated simultaneously. 
Only one of the nodes is throwing this error. The other three function normally.

Restarting Node-Red didn't solve the issue.

Another note, I have an identical Node-Red instance running on a different Raspberry Pi that works normally.

**Comment by seth350** [comment] 2018-11-21 16:48
Update:

Adding a small delay in front of the mssql-plus node seems to have corrected the issue. 
I don't know why though? There isn't any other query happening at the time the node is called and there is a good 5-10 seconds since one of the other nodes were called. 
Perhaps it takes a little longer to close the connection at times?

**Comment by pate313373** [comment] 2018-11-21 17:05
This is indeed a bug! You're just describing a workaround.
The fix is here: https://github.com/redconnect-io/node-red-contrib-mssql/pull/29

**Comment by seth350** [comment] 2018-11-21 17:07
> This is indeed a bug! You're just describing a workaround.
> The fix is here: [redconnect-io/node-red-contrib-mssql#29](https://github.com/redconnect-io/node-red-contrib-mssql/pull/29)

Sorry

**Comment by pate313373** [comment] 2019-01-28 15:24
There is still a bug:
I'm using two different connections. The databases both run on the same MSSQL instance.
After a few (parallel) rquests, one of the connections gets closed and stays closed. The other connection, can in the meanwhile still handle parallell requests.

So the issue is now about parallel connections, not parallel queries like before.

Thank you for the great job so far!

**Comment by mskorge** [comment] 2019-02-01 18:32
I'm seeing this as well...

**Comment by youngkzy** [comment] 2019-02-28 15:27
This Bug still exists.  I have 2 Databases which the first gets a reference to a product name.  The other database is the data for that product.  MSSQL was fully functional before 7 months ago before that change.  After I upgraded to the prior version and then today on the most recent version,  the initial queries are completely functional ONLY for one trial.  If I trigger the nodes again after they have run once, they fail.  I have to re-start Node-Red and I can then get the data from the system once more.

**Comment by youngkzy** [comment] 2019-03-07 16:14
How do you go about re-initializing the node? programmatically?  It works OK if you re-deploy, but after the error exists, it continues until re-deployment.   There is nothing which I know of that allows you to initialize these connections by flow logic, or is there?  The problem may be that you need to allow a re-connection point based on flow logic....

**Comment by youngkzy** [comment] 2019-04-09 17:47
in "mssql.js"
I was reviewing the code... just looking at it really.  
There was a syntax error noted in my javascript editor.    

Is there something missing at the '.then('  which would adjust behavior?     

node.on('input', function (msg) {
            mssqlCN.connect(node.id).then(()* =>* {        AT "*"  EXPECTED EXPRESSION                node.*status({                                                               AT "*" EXPECTED ":"
                    fill: 'blue',
                    shape: 'dot',
                    text: 'requesting'
                });

                var query = mustache.render(node.query, msg);

                if (!query || (query === '')) {
                    query = msg.payload;
                }

                var request = new mssqlCN.connection.Request();
                request.query(query).then(function (rows) {
                    i = 0;
                    r = rows;
                    m = msg;
                    rec(msg);
                }).catch(function (error) {
                    node.error(error);
                    node.status({
                        fill: 'red',
                        shape: 'ring',
                        text: 'Error'
                    });
                    msg.error = error;
                    node.send(msg);
                });
            }).catch(function (error) {
                node.error(error);
                node.status({
                    fill: 'red',
                    shape: 'ring',
                    text: 'Error'
                });
                msg.error = error;
                node.send(msg);
            });
        });

**Comment by MarkusBe** [comment] 2019-05-02 09:03
I have exactly the same issue. It works once, the second time it fails until I re-deploy the flow, that it works once again...

**Comment by Steve-Mcl** [comment] 2019-07-24 12:29
Hi all, I now believe this bug to be fixed in V0.2.1.

Closing issue ( for now :) ).

**Closed by Steve-Mcl** 2019-07-24 12:29 UTC
Labels: bug

**Comment by TobiasKorn** [comment] 2023-06-27 07:29
I still have the problem with actual version of node-red-contrib-mssql-plus (0.10.2). Concurrent requests on two MSSQL nodes, which share the same connection results in Connection Error in one of the nodes.

Using time delay (about 20ms) or using different connections helps, but its uncomfortable. In my flows I use many MSSQL nodes, which share the same connection. I cannot guarantee when they are beeing executed, because some are triggered by pressing a button in the UI.

**Comment by christianhubmann** [comment] 2023-10-20 16:39
Also seeing this problem with current version of 0.12.1, although it seems to disappear after some minutes in my case.
